spring:
    application:
        name: flexi-eureka

server:
    port: ${EUREKA-PORT:8761}

eureka:
    client:
        register-with-eureka: false
        fetch-registry: false
        service-url:
            defaultZone: http://eureka:${EUREKA-PORT:8761}/eureka/
    instance:
        hostname: eureka
        prefer-ip-address: false
        non-secure-port: 8761
    server:
        enable-self-preservation: false