spring:
    application:
        name: flexi-eureka

server:
    port: ${EUREKA-PORT:8761}

eureka:
    client:
        register-with-eureka: ${REGISTER_WITH_EUREKA:false}
        fetch-registry: ${FETCH_REGISTRY:false}